disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - function_parameter_count
  - file_length
  - todo
  - switch_case_alignment
  - trailing_whitespace
  - implicit_getter
  - redundant_string_enum_value
  - class_delegate_protocol

line_length: 150
type_name:
    max_length: 50

excluded:
  - Scripts
  - Pods
  - 'ConcordiumWalletTests/HelperClasses/Mocks/Generated'
