name: Build and test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: mxcl/xcodebuild@v1
      with:
        platform: iOS
        action: build
