name: Build and test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        scheme:
        - StagingNet
        - ProdTestNet
        - ProdMainNet
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build scheme '${{matrix.scheme}}'
      # Action uses deprecated features (https://github.com/mxcl/xcodebuild/issues/89).
      uses: mxcl/xcodebuild@v1
      with:
        platform: iOS
        scheme: "${{matrix.scheme}}"
        action: test
        code-coverage: true
