name: Build and test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: mxcl/xcodebuild@v1
      platform: iOS
      action: build
