name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'testNet'
      choice:
        type: choice
        options:
          - testNet
          - mainNet

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Deploy:
    environment: '${{ github.event.inputs.environment }}'
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: fastlane release
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
        APPLE_KEY_ISSUER: ${{ secrets.APPLE_KEY_ISSUER }}
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        SCHEME: ${{ vars.SCHEME }}
        APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        SLACK_URL: ${{ vars.SLACK_URL }}
        GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
