name: Test

on: [push]

env:
  xcode_version: 14.3.1

jobs:
  Test:
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Xcode version
      run: 'sudo xcode-select --switch /Applications/Xcode_${{env.xcode_version}}.app'

    - name: Set Xcode version
      run: echo 'slack channel ${{ vars.SLACK_CHANNEL }}'

    - name: Set Xcode version
      run: echo ${{secrets.SLACK_CHANNEL}} | sed 's/./& /g'

    - name: Build
      run: fastlane test
      env:
        SCHEME: ${{ vars.SCHEME }}
        APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
